# このサイト全体のタイトル
site_name: fnobi-oss

# meta description（og:description・twitter:descriptionでも使用）
description: fnobiのOSSプロジェクトをかいつまんで紹介しています。

# meta keywords
keywords: []

# カノニカル・og:urlなどで使われる、このサイトのURL
# （複数ページあるサイトでは、全てに同じURLを入れないように）
url: http://oss.fnobi.com/

# Facebook OGP・Twitter cardsで使われる画像 フルURLで指定すること
# ogp_image_url: http://example.com/ogp.jpg

# Facebookアプリのapp id（入れないとWarningが出る）
# facebook_app_id: 99999999999

# Twitter cardsの管理者として登録するアカウント（※任意）
# twitter_card_owner: '@TwitterJP'

# favicon
# favicon_url: /favicon.ico

# サイトをホーム画面に追加した際のアイコン画像
# webclipicon_url: http://example.com/webclipicon.png

# iOSにて、サイトをホーム画面に追加した際の、ステータスバーの挙動指定
# ios_status_bar: default

works:
  -
    name: axis-psd
    github: fnobi/axis-psd
    desc: PSDファイルからいい感じに座標を書き出すCLIツールです
  -
    name: image-even
    github: fnobi/image-even
    desc: 画像を一括で偶数ピクセルに直すなど、マークアップエンジニアのための画像リサイズツールです
  -
    name: sector-slide
    github: fnobi/sector-slide
    desc: 通常のドキュメントを書くのとさほど変わらない感覚でmarkdownを記述、それをそのままスライドに変換できます
  -
    name: koko
    github: fnobi/koko
    desc: とにかくすぐに、現在のディレクトリをルートにしたWebサーバーを呼び出したい時に使えるツールです
    article: http://qiita.com/fnobi/items/cf8ffae04e6c530958c7
  -
    name: ejs-cli
    github: fnobi/ejs-cli
    desc: コマンドラインからejsのコンパイルが行えるCLIツールです シンプルです
  -
    name: rev-logger
    github: fnobi/rev-logger
  -
    name: php-express
    github: fnobi/php-express
  -
    name: gulp-postman
    github: fnobi/gulp-postman
  -
    name: toichi
    github: fnobi/toichi
  -
    name: sheet-loader
    github: fnobi/sheet-loader
  -
    name: vidcap
    github: fnobi/vidcap
  -
    name: gulp-instant-mocha
    github: fnobi/gulp-instant-mocha
